[package]
name = "tree-sitter-grep"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.3.0", features = ["derive"] }
once_cell = "1.17.1"
rayon = "1.7.0"
regex = "1.8.2"
tree-sitter = "0.20.10"
tree-sitter-rust = "0.20.3"
walkdir = "2.3.3"

[lib]
name = "tree_sitter_grep"

[[bin]]
name = "tree-sitter-grep"
